//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Stomatologic.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int idAccount { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
        public Nullable<int> idUserType { get; set; }
        public string recordStatus { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
