//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cabinet_Stomatologic.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int idAppointment { get; set; }
        public Nullable<System.DateTime> dateAppointment { get; set; }
        public Nullable<System.TimeSpan> timeAppointemnt { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<int> idBill { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public Nullable<int> idPatient { get; set; }
        public Nullable<int> idProcedure { get; set; }
        public string recordStatus { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
        public virtual doctorProcedure doctorProcedure { get; set; }
    }
}
